version: "3.8"

services:
  netbirdoracle:
    build: .
    container_name: netbirdoracle
    volumes:
      - /home/wreath1553/.ssh:/root/.ssh

    environment:
      TZ: Asia/Kolkata
      REMOTE_USER: ${REMOTE_USER}
      REMOTE_IP: ${REMOTE_IP}
      CONTAINER_NAME: ${CONTAINER_NAME}
